name: nis2pyr
dependencies:
  - python>=3.7,<3.10
  - pip
  - pip:
    - tifffile == 2021.8.30
    - imagecodecs == 2021.8.26
    - opencv-python == 4.5.3.56
    - ome_types
    - nd2
    - dask
    - xarray
    - pytest

