name: PyPi

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish Python distribution to TestPyPi
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install build tool
      run: python -m pip install build --user

    - name: Build distribution
      run: python -m build

    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
