name: Test

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }} + Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.9]
        platform: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          
      - name: Download test images
        run: python scripts/download_testimages.py tests/data

      - name: Test + analyze code coverage
        run: pytest -v --cov=nis2pyr --cov-report term --cov-report=xml --input-dir=tests/data --output-dir=tests/data
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
